### ISSUE TITLE
Francesco's mail (in Italian)

### ISSUE THREAD

**Issue by ziorufus** [dkmfbk/premon#19]
- [x] **IMPORTANTE** Per i verbi multiword in PB (1.7 e ON5) le
  conceptualization sono generate usando la multiword (e.g., cut+up)
  e non la head (e.g. cut). Tuttavia, quando si creano i mapping a
  partire da NB10 e SL122C), la conceptualization creata per PB usa
  la head (cut) e non la multiword di cui non c'è traccia nella altre
  risorse (cut+up). Conseguenza: le due conceptualization hanno URI
  diverse e il mapping viene eliminato durante il filtraggio.
  Possibile soluzione: cambiare il modo con cui si generano le URI
  delle conceptualization in PropBankConverter, usando la head
  (prendere lemma da lemma.num) invece che l'intera multiword.
  Pensi sia fattibile? **DONE**
- [x] **IMPORTANTE** I mapping tra NB10 e VN32 sono _tutti_ scartati.
  Motivo: lavoriamo a livello di concettualizzazione e usiamo la
  stessa lexical entry (un _nome_) sia per NB che per VN. Chiaramente
  le classi di VN sono associate solotanto a _verbi_, e quindi le
  concettualizzazioni così create non sono valide. Soluzioni:
  
  (a) lavoriamo a livello di pmo:SemanticClass e pmo:SemanticRole,
      senza quindi tirare in ballo le lexical entry
  (b) usando WN cerchiamo il verbo in VerbNet che pià corrisponde al
      nome in nombank (dovrebbe esserci in generale)
  
  Io sono a favore di (a).
  Marco ed io ne abbiamo parlato un po' stamattina e saremmo orientati
  sulla (b). Ci siamo infatti resi conto che nei frame NB, praticamente
  sempre, insieme al link a VN viene fornito il link a PB (e.g., seller.01
  va in sell.01 e in vn X.Y.Z). Ora se si prende il verbo di PB, questo
  sembra essere sempre membro della classe VN. Quindi, possiamo costruire
  la Conceptualization di VN usando
  
  lexical entry = lemma PB (e.g., sell.01 -> sell)
  part of speech = v
  concept = classe VN (nome e numero)
  
  Pensi sia fattibile in pratica?
  **Fatto! Unico problema: se NON c'è il mapping di PropBank, per ora ignora anche quello di VerbNet (non so se capita, ma potrebbe)**
- [x] **IMPORTANTE** 8584 role mapping su 9572 non sono validi tra FN15 e
  FN16. Le URI dei ruoli FN15 sono per lo più generate come
  ruolo@ruolo, invece che frame@ruolo. Vedo che la cosa è deliberata
  nel tuo codice. Puoi per favore controllare? **DONE**
- [x] l'opzione -i viene applicata soltanto alla proprietà 'folder' e
  _non_ agli altri percorsi (e.g., vnpath usato per linkare a VN).
  Per semplicità suggerisco di toglierla e lasciare che tutti i
  percorsi facciano riferimento alla working dir. **See issue #12**
- [x] nel fare debug ho visto che spesso e volentieri viene richiesta la
  creazione di mapping con un solo pmo:item (cosa che giustamente
  viene ignorata dal codice che crea i mapping) - ho messo un warning
  per segnalare questi casi, magari prova a investigare e se pensi
  sia OK togli pure
  **L'avevo notato anche io, e proprio per questo avevo messo il controllo. La maggior parte delle volte, accade perché qualcosa non viene trovato un una Map (tipo il VerbNet id).**
- [x] con le proprietà default (src/main/assembly/premonitor.properties)
  premonitor non richiede opzioni a riga di comando aggiuntive, se
  non le seguenti due che vorrei però rendere opzionali:
  
  --wordnet --> se omessa, default è resources/wordnet-3.1/wn31.nt.gz
  --wordnet-sensekeys --> se omessa, in qualche modo dovrebbe
                          caricare un file wn30-senseKeys.tsv incluso
                          da qualche parte in premonitor
- [x] il file wn30-senseKeys.tsv possiamo metterlo sotto version control
  e distribuirlo col tool, oppure non possiamo per questioni di
  licenze?

**Comment by fracorco** [comment]
no roles mapped from NB10 to VN32 (in resource NB10). Generated VN conceptualization URIs still use pos tag 'n': 

http://premon.fbk.eu/resource/conceptualization-n-seer-vn32-characterize-29.2-agent

apart this, we lose 716 class mappings, but this could be OK (I checked a few of them and the verb lemma was not part of the VN class)
