### ISSUE TITLE
Properties nif:anchorOf, nif:isString, dct:identifier should be functional

### ISSUE THREAD

**Issue by fracorco** [dkmfbk/premon#20]
See counter-examples:

   http://premon.fbk.eu/resource/nb10-admirer.01-example1?char=0,8
   http://premon.fbk.eu/resource/pb17-slim.01-example0
   http://premon.fbk.eu/resource/conceptualization-n-export-fn16-exporting

**Comment by ziorufus** [comment]
- Per quanto riguarda il markable, ho corretto.
- Per quanto riguarda l'esempio, è un bug della risorsa PB17
- Per la LU di FN (riguardo l'ID), lo sapevamo già perché creiamo la URI ripulendo il nome della LU

**Comment by rospocher** [comment]
http://premon.fbk.eu/resource/pb17-slim.01-example0
two examples, from different frame files (slim.xml and slim-down), but on the same roleset (slim.01) get merged... 
Should be treated as separate examples (on the same semantic class)

**Comment by ziorufus** [comment]
See issue #27
