### ISSUE TITLE
Don't generate triples with property pm:example

### ISSUE THREAD

**Issue by fracorco** [dkmfbk/premon#23]
This happens in VN32, where this property links a syntactic frame to the corresponding example(s).

**Comment by ziorufus** [comment]
Mi scrivi un esempio?

**Comment by fracorco** [comment]
select ?s ?o ?g where { graph ?g { ?s pmo:example ?o } }

pm:vn32-accept-77_frame_1   pm:vn32-accept-77_frame_1_ex    pm:vn32-ex
pm:vn32-accept-77_frame_2   pm:vn32-accept-77_frame_2_ex    pm:vn32-ex
pm:vn32-accept-77_frame_3   pm:vn32-accept-77_frame_3_ex    pm:vn32-ex
...
