### ISSUE TITLE
Add FN version to URIs of FN examples

### ISSUE THREAD

**Issue by fracorco** [dkmfbk/premon#24]
This is necessary in order to distinguish between FN 1.5 and FN 1.6 examples, as their URIs currently collide and this may cause problems to persons using our datasets without named graphs.

**Comment by ziorufus** [comment]
Io metterei sempre la versione negli esempi, così almeno togliamo ogni possibile problema futuro.

**Comment by fracorco** [comment]
source and version, agreed
