### ISSUE TITLE
pmo:Inflection(s) should be defined in a single graph

### ISSUE THREAD

**Issue by fracorco** [dkmfbk/premon#26]
Currently, they are created both in pm:pb17 and pm:pbon5.
We have 222 of them in total. As I see them more like TBox constants, I suggest putting their triples (e.g., pmopb:person, pmopb:form, ...) in graph pm:tbox.

**Comment by ziorufus** [comment]
Mi mandi un esempio?

**Comment by fracorco** [comment]
select distinct ?s ?p ?o ?g where { ?s a pmopb:Inflection . graph ?g { ?s ?p ?o } }

s   p   o   g
pm:inflection-full-past-active  rdf:type    pmopb:Inflection    pm:pb17
pm:inflection-full-past-active  rdf:type    pmopb:Inflection    pm:pbon5
...
